/******************************************************************************
 *                SophonJS: An embedded javascript engine                     *
 *                                                                            *
 * Copyright (c) 2015 Gong Ke                                                 *
 * All rights reserved.                                                       *
 *                                                                            *
 * Redistribution and use in source and binary forms, with or without         *
 * modification, are permitted provided that the following conditions are     *
 * met:                                                                       *
 * 1.Redistributions of source code must retain the above copyright notice,   *
 * this list of conditions and the following disclaimer.                      *
 * 2.Redistributions in binary form must reproduce the above copyright        *
 * notice, this list of conditions and the following disclaimer in the        *
 * documentation and/or other materials provided with the distribution.       *
 * 3.Neither the name of the Gong Ke; nor the names of its contributors may   *
 * be used to endorse or promote products derived from this software without  *
 * specific prior written permission.                                         *
 *                                                                            *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS    *
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  *
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR     *
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR           *
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,      *
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,        *
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR         *
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF     *
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING       *
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         *
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               *
 *****************************************************************************/

#ifndef _SOPHON_FRAME_H_
#define _SOPHON_FRAME_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "sophon_types.h"
#include "sophon_value.h"
#include "sophon_gc.h"
#include "sophon_hash.h"

/**\brief Frame type*/
typedef enum {
	SOPHON_FRAME_GLOBAL, /**< Global frame*/
	SOPHON_FRAME_DECL,   /**< Declaration frame*/
	SOPHON_FRAME_CATCH,  /**< Catch block*/
	SOPHON_FRAME_WITH    /**< With block*/
} Sophon_FrameType;

/**\brief Stack frame*/
struct Sophon_Frame_s {
	SOPHON_GC_HEADER
	Sophon_U8     type;   /**< Frame type*/
	Sophon_Frame *bottom; /**< The bottom frame*/
};

/**\brief Declaration frame*/
typedef struct {
	Sophon_Frame     frame;    /**< Base frame data*/
	Sophon_U8        argc;     /**< Arguments count*/
	Sophon_Hash      var_hash; /**< Hash table of variant generated by 'eval'*/
	Sophon_Function *func;     /**< The function used this frame*/
	Sophon_Value     thisv;    /**< This value*/
	Sophon_Value     argsv;    /**< The arguments value*/
	Sophon_Value     v[1];     /**< Function arguments and variants buffer*/
} Sophon_DeclFrame;

/**\brief Catch frame*/
typedef struct {
	Sophon_Frame     frame;    /**< Base frame data*/
	Sophon_Value     namev;    /**< Name of the exception*/
	Sophon_Value     excepv;   /**< Exception value*/
} Sophon_CatchFrame;

/**\brief With frame*/
typedef struct {
	Sophon_Frame     frame;    /**< Base frame data*/
	Sophon_Value     withv;    /**< This value*/
} Sophon_WithFrame;

/**\brief Global frame*/
typedef Sophon_WithFrame Sophon_GlobalFrame;

/**
 * \brief Push a frame into the stack
 * \param[in] vm The current virtual machine
 * \param type frame type
 * \param[in] func The declaration frame's function
 * \param argc The real argument count of the declaration frame
 */
extern Sophon_Frame* sophon_frame_push (Sophon_VM *vm,
						Sophon_FrameType type,
						Sophon_Function *func,
						Sophon_U8 argc);

#ifdef __cplusplus
}
#endif

#endif

